services:
  mysql:
    restart: always
    image: mariadb:11.8
    command: ['mariadbd', '--character-set-server=utf8mb4']
    ports:
      - "${MYSQL_PORT_HOST:-3376}:3306"
    volumes:
      - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-openemr}
      MYSQL_USER: ${MYSQL_USER:-openemr}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-openemr}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root}"]
      timeout: 5s
      retries: 5
      interval: 10s

  openemr:
    restart: always
    image: openemr/openemr:flex
    ports:
      - "${HTTP_PORT_HOST:-8370}:80"
      - "${HTTPS_PORT_HOST:-9370}:443"
    volumes:
      - .:/var/www/localhost/htdocs/openemr:rw
      - logvolume:/var/log
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-openemr}
      MYSQL_PASS: ${MYSQL_PASSWORD:-openemr}
      OE_USER: ${OE_USER:-admin}
      OE_PASS: ${OE_PASS:-pass}
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
      EASY_DEV_MODE: "yes"
      EASY_DEV_MODE_NEW: "yes"
      DEVELOPER_TOOLS: "yes"
      FORCE_NO_BUILD_MODE: "yes"
      EMPTY: "yes"
      OPENEMR_DOCKER_ENV_TAG: easy-dev-docker
    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    restart: always
    image: phpmyadmin
    ports:
      - "${PMA_PORT_HOST:-8310}:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  databasevolume: {}
  logvolume: {}
